### ISSUE TITLE
Mobile Processing Lab's recycler still consumes ReplacementParts

### ISSUE THREAD

**Issue by fraz86** [BobPalmer/USI-LS#78] opened 2016-02-17 06:19 UTC
MKS/OKS recyclers no longer consume ReplacementParts, however, the recycler for the stock lab (added by LSModule.cfg) still requires ReplacementParts as in input resource.

**Comment by fat-lobyte** [comment] 2016-02-29 17:11
This is a duplicate of #76

**Closed** 2016-12-31 18:19 UTC
