### ISSUE TITLE
Orbital Stations show as "Landed" in Life Support tab

### ISSUE THREAD

**Issue by eucarya** [BobPalmer/USI-LS#81] opened 2016-02-20 10:23 UTC
![minorbug1](https://cloud.githubusercontent.com/assets/17260269/13196071/d13308c8-d7bb-11e5-8e23-b0ace4a28282.png)

**Comment by fat-lobyte** [comment] 2016-02-22 16:56
This is a duplicate of issue #68 . Please close this one, to avoid clutter.

**Closed** 2016-03-02 19:16 UTC
